routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('classes','ClassController@classes');
Route::post('classList','ClassController@classList');
Route::resource('class','ClassController');
Route::get('class/{id}/delete','ClassController@destroy');

app/Http/Controllers/ClassController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Classes;
use App\ClassLevels;
use App\College;
/*use Input;
use Validator;
use Redirect;
use View;*/


class ClassController extends Controller
{
	function classes(Request $request){
		return view('classes.list');
	}

	function classList(Request $request){

		$columns = array(
			1 =>'college_name',
			2 =>'title',
			3 =>'levels',
		);  
		$totalData = Classes::count();            
		$totalFiltered = $totalData;
		$limit = $request->input('length');
		$start = $request->input('start');
		/*$order = $columns[$request->input('order.0.column')];
		$dir = $request->input('order.0.dir');*/

		if(empty($request->input('search.value')))
		{            
			$institutes = Classes::offset($start)
			->limit($limit)
			->orderBy('id', 'DESC')
			->get();
		}else {
			$search = $request->input('search.value'); 

			$institutes =  Classes::leftJoin('college', 'college.id', '=', 'class.college_id')
			->leftJoin('class_levels', 'class_levels.id', '=', 'class.id')
			->where('class.id','LIKE',"%{$search}%")
			->orWhere('class.title', 'LIKE',"%{$search}%")
			->orWhere('college.name', 'LIKE',"%{$search}%")
			->orWhere('class_levels.level_name', 'LIKE',"%{$search}%")			
			->offset($start)
			->limit($limit)
			->orderBy('class.id', 'DESC')
			->get();

			

			$totalFiltered = Classes::leftJoin('college', 'college.id', '=', 'class.college_id')
			->leftJoin('class_levels', 'class_levels.id', '=', 'class.id')
			->where('class.id','LIKE',"%{$search}%")
			->orWhere('class.title', 'LIKE',"%{$search}%")
			->orWhere('college.name', 'LIKE',"%{$search}%")
			->orWhere('class_levels.level_name', 'LIKE',"%{$search}%")			
			->count();
		}
		$data = array();
		if(!empty($institutes))
		{
			foreach ($institutes as $key=>$institute)
			{
				$getCollegeName = College::find($institute->college_id);
				$getLevels = ClassLevels::where('class_id', $institute->id)->get();
				$levelsName = [];
				if(count($getLevels) > 0) {
					foreach($getLevels as $r=>$t) {
						$levelsName[] = $t->level_name;
					}
				}
				$nestedData['college_name'] = $getCollegeName->name;
				$nestedData['title'] = $institute->title;
				$nestedData['levels'] = implode(",", $levelsName);
				$nestedData['action'] = '<a href="'.url('/class/'.$institute->id.'/delete').'" class="del"><span class="glyphicon glyphicon-trash"></span> 
				</a><a href="'.url('/class/'.$institute->id.'/edit').'" class="edit"><span class="glyphicon glyphicon-edit"></span></a>';
				$data[] = $nestedData;
			}

		}
		$json_data = array(
			"draw"            => intval($request->input('draw')),  
			"recordsTotal"    => intval($totalData),  
			"recordsFiltered" => intval($totalFiltered), 
			"data"            => $data   
		);            
		echo json_encode($json_data); 
	}

	public function create()
    {
       /* if (! Gate::allows('product_create')) {
            return abort(401);
        }*/
        
        $colleges = \App\College::get()->pluck('name', 'id')->prepend('Select College', '');
       

        return view('classes.create', compact('colleges'));
    }

    public function store(Request $request)
    {     
    	$validatedData = $request->validate([
            'title'       => 'required',
            'email' => 'required|email|unique:class,email',
            'price' => 'required',
            'description' => 'required',
            'syllabus' => 'required|max:8000|mimes:doc,docx,pdf',
            'college_id' => 'required',
            'contact_number' => 'required',
            'level' => 'required|array' 
        ]);
        
        

        $insertArray = $request->all();      
        $filename = '';
        if($request->hasFile('syllabus')) {
        	$file = $request->file('syllabus');   
			$filename = $file->getClientOriginalName();
			   
			//Move Uploaded File
			$destinationPath = 'public/uploads';
			$file->move($destinationPath,$file->getClientOriginalName());
        }

        $insertArray['syllabus'] = $filename;
        
        // dd($insertArray);
        $newClass = Classes::create($insertArray);
        $class_id = $newClass->id;    

        $levels = $request->level;
        
        foreach($levels as $k => $v) {
        	if($v != null) {
        	$addLevel = new ClassLevels;
        	$addLevel->class_id = $class_id;
        	$addLevel->level_name = $v;
        	$addLevel->save();
        	}
        }
       

        return redirect('classes');
    }

    public function edit($id)
    {
        
        
        $class = Classes::find($id);

        $colleges = \App\College::get()->pluck('name', 'id')->prepend('Select College', '');

        $levels = ClassLevels::where('class_id', $id)->get();
        
        return view('classes.edit', compact('colleges', 'levels', 'class', 'id'));
    } 

    public function update(Request $request, $id)
    {     
    	$validatedData = $request->validate([
            'title'       => 'required',
            'email' => 'required|email',
            'price' => 'required',
            'description' => 'required',
            'syllabus' => 'max:8000|mimes:doc,docx,pdf',
            'college_id' => 'required',
            'contact_number' => 'required',
            'level' => 'required|array' 
        ]);
        
        

        $insertArray = $request->all();      
        $filename = '';
        if($request->hasFile('syllabus')) {
        	$file = $request->file('syllabus');   
			$filename = $file->getClientOriginalName();
			   
			//Move Uploaded File
			$destinationPath = 'public/uploads';
			$file->move($destinationPath,$file->getClientOriginalName());
        }

        $insertArray['syllabus'] = $filename;
        
        // dd($insertArray);
        $classUpdate = Classes::findOrFail($id);
        $classUpdate->update($insertArray);
        $class_id = $id;    

        $levels = $request->level;

        $deleteOld = ClassLevels::where('class_id', $id)->delete();
        
        foreach($levels as $k => $v) {
        	if($v != null) {
        	$addLevel = new ClassLevels;
        	$addLevel->class_id = $class_id;
        	$addLevel->level_name = $v;
        	$addLevel->save();
        	}
        }
       

        return redirect('classes');
    }

    public function destroy($id)
    {
        // if (! Gate::allows('branch_delete')) {
        //     return abort(401);
        // }
        $deleteLevels = ClassLevels::where('class_id', $id)->delete();
        $class = Classes::findOrFail($id);
        if($class->syllabus != '' && file_exists('public/uploads/'.$class->syllabus)){
            unlink('public/uploads/'.$class->syllabus);
        }
        $class->delete();

        return redirect()->back();
    }         
}

resources/views/classes/create.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-title">Class</h3>
    {!! Form::open(['method' => 'POST', 'route' => ['class.store'], 'files' => true,]) !!}

    <div class="panel panel-default">
        <div class="panel-heading">
            Create
        </div>
        
        <div class="panel-body">
            <div class="row">
                <div class="col-xs-6 form-group">
                    {!! Form::label('college', 'College', ['class' => 'control-label']) !!}
                    {!! Form::select('college_id', $colleges, old('college'), ['class' => 'form-control select2']) !!}
                    <p class="help-block"></p>
                </div>

                <div class="col-xs-6 form-group">
                    {!! Html::decode(Form::label('title', 'title <span class="text-danger">*</span>', ['class' => 'control-label'])) !!}
                    {!! Form::text('title', old('title'), ['class' => 'form-control', 'placeholder' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('title'))
                        <p class="help-block">
                            {{ $errors->first('title') }}
                        </p>
                    @endif
                </div>              
            
                
            </div>

            <div class="row">
                 <div class="col-xs-6 form-group">
                    {!! Html::decode(Form::label('contact_number', 'Contact Number <span class="text-danger">*</span>', ['class' => 'control-label'])) !!}
                    {!! Form::number('contact_number', old('contact_number'), ['class' => 'form-control', 'placeholder' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('contact_number'))
                        <p class="help-block">
                            {{ $errors->first('contact_number') }}
                        </p>
                    @endif
                </div>
                <div class="col-xs-6 form-group">
                    {!! Form::label('email', 'Email', ['class' => 'control-label']) !!}
                    {!! Form::email('email', old('email'), ['class' => 'form-control', 'placeholder' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('email'))
                        <p class="help-block">
                            {{ $errors->first('email') }}
                        </p>
                    @endif
                </div>               
                
                
            </div>
            <div class="row">
                <div class="col-xs-6 form-group">
                    {!! Html::decode(Form::label('price', 'Price <span class="text-danger">*</span>', ['class' => 'control-label'])) !!}
                    {!! Form::number('price', old('price'), ['class' => 'form-control', 'placeholder' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('price'))
                        <p class="help-block">
                            {{ $errors->first('price') }}
                        </p>
                    @endif
                </div>
                <div class="col-xs-6 form-group">
                    {!! Html::decode(Form::label('description', 'Description <span class="text-danger">*</span>', ['class' => 'control-label'])) !!}
                    {!! Form::textarea('description', old('description'), ['class' => 'form-control', 'placeholder' => '', 'rows' => '5']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('description'))
                        <p class="help-block">
                            {{ $errors->first('description') }}
                        </p>
                    @endif
                </div>  
                
                 
            </div>            

            <div class="row after-add-more">
                <div class="col-xs-6 form-group">
                    {!! Html::decode(Form::label('syllabus', 'Syllabus <span class="text-danger">*</span>', ['class' => 'control-label'])) !!}
                    {!! Form::file('syllabus', ['class' => 'form-control', 'style' => 'margin-top: 4px;']) !!}
                    
                    <p class="help-block"></p>
                    @if($errors->has('syllabus'))
                        <p class="help-block">
                            {{ $errors->first('syllabus') }}
                        </p>
                    @endif
                </div>
                <div class="col-xs-6 form-group">
                    {!! Html::decode(Form::label('level', 'Level <span class="text-danger">*</span>', ['class' => 'control-label'])) !!}
                    {!! Form::text('level[]', null, ['class' => 'form-control', 'placeholder' => '','required' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('level'))
                        <p class="help-block">
                            {{ $errors->first('level') }}
                        </p>
                    @endif
                </div>
                <div class="col-xs-6 form-group input-group-btn" style="margin-top: 25px;"> 
                    <button class="btn btn-success add-more" type="button"><i class="glyphicon glyphicon-plus"></i> Add</button>
                </div>
            </div>
            <div class="row copy " style="display: none;">
                <div class="col-xs-6 form-group control-group">
                    
                    {!! Form::text('level[]', null, ['class' => 'form-control', 'placeholder' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('level'))
                        <p class="help-block">
                            {{ $errors->first('level') }}
                        </p>
                    @endif
                
                  <button class="btn btn-danger remove " type="button"><i class="glyphicon glyphicon-remove"></i> Remove</button>
                </div>
            </div>
                     
    
        </div>
    </div>

    {!! Form::submit('Save', ['class' => 'btn btn-danger']) !!}
     <a href="{{ url('classes') }}" class="btn btn-default">Cancel</a>
    {!! Form::close() !!}
@stop
<script type="text/javascript" src="{{url('/public/js/jquery.min.js')}}"></script>



<script type="text/javascript">
    $(document).ready(function() {


      $(".add-more").click(function(){ 
        
          var html = $(".copy").html();
          $(".after-add-more").after(html);
      });


      $("body").on("click",".remove",function(){ 
          $(this).parents(".control-group").remove();
      });


    });


    function isNumberKey(evt,id)
    {
        try{
            var charCode = (evt.which) ? evt.which : event.keyCode;
      
            if(charCode==46){
                var txt=document.getElementById(id).value;
                if(!(txt.indexOf(".") > -1)){
        
                    return true;
                }
            }
               if(charCode == 118){
               return true;
            }
            if (charCode > 31 && (charCode < 48 || charCode > 57) )
                return false;

            return true;
        }catch(w){
            //alert(w);
        }
    }

</script>

resources/views/classes/edit.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-title">Class</h3>
     {!! Form::model($class, ['method' => 'PUT', 'route' => ['class.update', $class->id], 'files' => true,]) !!}

    <div class="panel panel-default">
        <div class="panel-heading">
            Create
        </div>
        
        <div class="panel-body">
            <div class="row">
                <div class="col-xs-6 form-group">
                    {!! Form::label('college', 'College', ['class' => 'control-label']) !!}
                    {!! Form::select('college_id', $colleges, old('college'), ['class' => 'form-control select2']) !!}
                    <p class="help-block"></p>
                </div>

                <div class="col-xs-6 form-group">
                    {!! Html::decode(Form::label('title', 'title <span class="text-danger">*</span>', ['class' => 'control-label'])) !!}
                    {!! Form::text('title', old('title'), ['class' => 'form-control', 'placeholder' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('title'))
                        <p class="help-block">
                            {{ $errors->first('title') }}
                        </p>
                    @endif
                </div>              
            
                
            </div>

            <div class="row">
                 <div class="col-xs-6 form-group">
                    {!! Html::decode(Form::label('contact_number', 'Contact Number <span class="text-danger">*</span>', ['class' => 'control-label'])) !!}
                    {!! Form::number('contact_number', old('contact_number'), ['class' => 'form-control', 'placeholder' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('contact_number'))
                        <p class="help-block">
                            {{ $errors->first('contact_number') }}
                        </p>
                    @endif
                </div>
                <div class="col-xs-6 form-group">
                    {!! Form::label('email', 'Email', ['class' => 'control-label']) !!}
                    {!! Form::email('email', old('email'), ['class' => 'form-control', 'placeholder' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('email'))
                        <p class="help-block">
                            {{ $errors->first('email') }}
                        </p>
                    @endif
                </div>               
                
                
            </div>
            <div class="row">
                <div class="col-xs-6 form-group">
                    {!! Html::decode(Form::label('price', 'Price <span class="text-danger">*</span>', ['class' => 'control-label'])) !!}
                    {!! Form::number('price', old('price'), ['class' => 'form-control', 'placeholder' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('price'))
                        <p class="help-block">
                            {{ $errors->first('price') }}
                        </p>
                    @endif
                </div>
                <div class="col-xs-6 form-group">
                    {!! Html::decode(Form::label('description', 'Description <span class="text-danger">*</span>', ['class' => 'control-label'])) !!}
                    {!! Form::textarea('description', old('description'), ['class' => 'form-control', 'placeholder' => '', 'rows' => '5']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('description'))
                        <p class="help-block">
                            {{ $errors->first('description') }}
                        </p>
                    @endif
                </div>  
                
                 
            </div>            

            <div class="row after-add-more">
                <div class="col-xs-6 form-group">
                    {!! Html::decode(Form::label('syllabus', 'Syllabus <span class="text-danger">*</span>', ['class' => 'control-label'])) !!}
                    {!! Form::file('syllabus', ['class' => 'form-control', 'style' => 'margin-top: 4px;']) !!}
                    
                    <p class="help-block"></p>
                    @if($errors->has('syllabus'))
                        <p class="help-block">
                            {{ $errors->first('syllabus') }}
                        </p>
                    @endif
                </div>

                @if(count($levels) > 0)
                @foreach($levels as $h => $b)
                <div class="col-xs-4 form-group">
                    {!! Html::decode(Form::label('level', 'Level <span class="text-danger">*</span>', ['class' => 'control-label'])) !!}
                    {!! Form::text('level[]', $b->level_name, ['class' => 'form-control', 'placeholder' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('level'))
                        <p class="help-block">
                            {{ $errors->first('level') }}
                        </p>
                    @endif
                </div>
                @endforeach
                @endif
                <div class="col-xs-2 form-group input-group-btn " style="margin-top: 25px;"> 
                <button class="btn btn-success add-more" type="button"><i class="glyphicon glyphicon-plus"></i> Add</button>
            </div>                
            </div>
            
            <div class="row copy " style="display: none;">
                <div class="col-xs-6 form-group control-group">
                    
                    {!! Form::text('level[]', null, ['class' => 'form-control', 'placeholder' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('level'))
                        <p class="help-block">
                            {{ $errors->first('level') }}
                        </p>
                    @endif
                
                  <button class="btn btn-danger remove " type="button"><i class="glyphicon glyphicon-remove"></i> Remove</button>
                </div>
            </div>
                     
    
        </div>
    </div>

    {!! Form::submit('Save', ['class' => 'btn btn-danger']) !!}
     <a href="{{ url('classes') }}" class="btn btn-default">Cancel</a>
    {!! Form::close() !!}
@stop
<script type="text/javascript" src="{{url('/public/js/jquery.min.js')}}"></script>



<script type="text/javascript">
    $(document).ready(function() {


      $(".add-more").click(function(){ 
        
          var html = $(".copy").html();
          $(".after-add-more").after(html);
      });


      $("body").on("click",".remove",function(){ 
          $(this).parents(".control-group").remove();
      });


    });


    function isNumberKey(evt,id)
    {
        try{
            var charCode = (evt.which) ? evt.which : event.keyCode;
      
            if(charCode==46){
                var txt=document.getElementById(id).value;
                if(!(txt.indexOf(".") > -1)){
        
                    return true;
                }
            }
               if(charCode == 118){
               return true;
            }
            if (charCode > 31 && (charCode < 48 || charCode > 57) )
                return false;

            return true;
        }catch(w){
            //alert(w);
        }
    }

</script>

resources/views/classes/list.blade.php
@extends('layouts.app')
@section('content')
 <a href="{{ route('class.create') }}" class="btn btn-success">Add New</a>

<div class="panel-body"> 
  <div class="panel-body">   
    <div class="row">         
      <table class="table table-bordered" id="institute_table" style="width:100%">

        <thead>
          <th>College</th>
          <th>Class</th>
          <th>Levels</th>
          <th>Action</th>

        </thead>        

      </table> 
    </div>
  </div>

</div>
@endsection

<script type="text/javascript" src="{{url('/public/js/jquery.min.js')}}"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.10.12/datatables.min.css"/>
 
<script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.10.12/datatables.min.js"></script>
 

<script>

  $(document).ready(function(){

// Data table for serverside

$('#institute_table').DataTable({

  "processing": true,

  "serverSide": true,
  "pageLength": 5,

  "ajax":{

    "url": "{{ url('classList') }}",

    "dataType": "json",

    "type": "POST",

    "data":{ _token: "{{csrf_token()}}",route:'classList'}

  },

  "columns": [
  { "data": "college_name" },
  { "data": "title" },
  { "data": "levels" },
  { "data": "action" }

  ],

  aoColumnDefs: [

  {

    bSortable: false,

    aTargets: [ -1 ]

  }

  ]  



});
});
</script>